version: "2"

services:

  tester:
    command: [ "/mnt/app/src/testit.sh" ]
    depends_on:
      - ffdriver
      - crdriver
    domainname: experiment.dev
    hostname: tester
    image: datihein/flask-helloworld-test:1.0.0
    networks:
      app-test-net:
        aliases:
          - tester.experiment.dev
    volumes_from:
      - container:dv-helloworldtls-src
      - container:dv-cert-tester-experiment-dev
    working_dir: /mnt/app/src

  ffdriver:
    image: datihein/selenium-standalonefirefox-3.0.1-ferrium-tls:1.0.0
    networks:
      - app-test-net

  crdriver:
    image: datihein/selenium-standalonechrome-3.0.1-ferrium-tls:1.0.0
    networks:
      - app-test-net

networks:
  app-test-net:
    driver: bridge
